"""Strict validation and import helpers for externally generated YAML."""

import os
from typing import Any, Dict, List

import yaml

from .schema_aliases import canonicalize_inventory_document
from .legacy_field_policy import canonicalize_legacy_document
from .validate_service import VALIDATION_MODE_DOCUMENT, validate_yaml_file
from .validators import format_validation_errors
from .yaml_ops import load_yaml


def _error_payload(
    error_code: str,
    message: str,
    *,
    errors: List[str] = None,
    warnings: List[str] = None,
) -> Dict[str, Any]:
    errors = list(errors or [])
    warnings = list(warnings or [])
    return {
        "ok": False,
        "error_code": str(error_code or "unknown_error"),
        "message": str(message or ""),
        "report": {
            "error_count": len(errors),
            "warning_count": len(warnings),
            "errors": errors,
            "warnings": warnings,
        },
    }


def validate_candidate_yaml(path: str, *, fail_on_warnings: bool = True) -> Dict[str, Any]:
    """Validate a candidate YAML file generated by external tools.

    This is the strict-import wrapper around the shared validation service.
    It keeps import-specific error wording while delegating the actual YAML
    loading + document validation to ``validate_yaml_file``.

    Args:
        path: Candidate YAML path.
        fail_on_warnings: When True, warnings are treated as blocking failures.
    """
    candidate = os.path.abspath(str(path or "").strip())
    if not candidate:
        return _error_payload("invalid_path", "Candidate YAML path is required.")

    result = dict(
        validate_yaml_file(
            candidate,
            mode=VALIDATION_MODE_DOCUMENT,
            fail_on_warnings=fail_on_warnings,
        )
        or {}
    )
    if result.get("ok"):
        return result

    error_code = str(result.get("error_code") or "")
    if error_code == "file_not_found":
        result["message"] = f"Candidate YAML not found: {candidate}"
        return result
    if error_code == "load_failed":
        message = str(result.get("message") or "")
        prefix = "Failed to load YAML: "
        if message.startswith(prefix):
            message = message[len(prefix):]
        result["message"] = f"Failed to load candidate YAML: {message}"
        return result
    if error_code == "validation_failed":
        report = dict(result.get("report") or {})
        errors = list(report.get("errors") or [])
        result["message"] = format_validation_errors(errors, prefix="Import validation failed")
        return result
    return result


def import_validated_yaml(
    candidate_path: str,
    target_path: str,
    *,
    mode: str = "create_new",
    overwrite: bool = False,
) -> Dict[str, Any]:
    """Import a candidate YAML file after strict validation.

    Current supported mode:
        - ``create_new``: write to a new/selected YAML path.
    """
    mode = str(mode or "create_new").strip().lower()
    if mode != "create_new":
        return _error_payload("unsupported_mode", f"Unsupported import mode: {mode}")

    validation = validate_candidate_yaml(candidate_path, fail_on_warnings=True)
    if not validation.get("ok"):
        return {
            "ok": False,
            "error_code": "validation_failed",
            "message": validation.get("message") or "Candidate YAML failed validation.",
            "report": validation.get("report") or {},
        }

    destination = os.path.abspath(str(target_path or "").strip())
    if not destination:
        return _error_payload("invalid_target_path", "Target YAML path is required.")

    suffix = os.path.splitext(destination)[1].lower()
    if suffix not in {".yaml", ".yml"}:
        return _error_payload("invalid_target_suffix", "Target path must end with .yaml or .yml")

    if os.path.exists(destination) and not overwrite:
        return _error_payload("target_exists", f"Target YAML already exists: {destination}")

    target_dir = os.path.dirname(destination)
    if target_dir:
        os.makedirs(target_dir, exist_ok=True)

    try:
        data = load_yaml(candidate_path)
        data, alias_errors = canonicalize_inventory_document(data)
        if alias_errors:
            return _error_payload(
                "validation_failed",
                format_validation_errors(alias_errors, prefix="Import validation failed"),
                errors=alias_errors,
                warnings=[],
            )
        legacy_result = canonicalize_legacy_document(data)
        if not legacy_result.get("ok"):
            return _error_payload(
                "validation_failed",
                str(legacy_result.get("message") or "Import validation failed"),
                errors=[str(legacy_result.get("message") or "Import validation failed")],
                warnings=[],
            )
        data = legacy_result.get("data")
        with open(destination, "w", encoding="utf-8") as handle:
            yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False)
    except Exception as exc:
        return _error_payload("write_failed", f"Failed to write imported YAML: {exc}")

    return {
        "ok": True,
        "message": "Imported validated YAML successfully.",
        "target_path": destination,
        "report": validation.get("report") or {},
    }
